### ISSUE TITLE
Каскадная модификация внутри блока нормально?

### ISSUE THREAD

**Issue by madbonez** [nicothin/idiomatic-pre-CSS#12]
В секции "Очередность написания в контексте селектора" читаю
 // Этот блок простилизован в другом файле, тут только каскадная модификация
  .fp-tableCell { ... }

Но это же зависимость от контекста! Те какой то где угодно вложенный блок сможет мне поменять стили в окружении. Как я понимаю методологию такого как раз все и стараются избежать. Или тут есть какие то нюансы?
ПС: в БЭМ новичок

**Comment by nicothin** [comment]
Это зависимость от контекста.

> Те какой то где угодно вложенный блок сможет мне поменять стили в окружении

Не обязательно

> Как я понимаю методологию такого как раз все и стараются избежать.

Именно так.

`.fp-tableCell` - один из селекторов пакета fullPage.js, установленного в `node_modules/`, в которой мы ничего не правим.
