### ISSUE TITLE
Опечатка: бЕм -> бЭм

### ISSUE THREAD

**Issue by veged** [nicothin/idiomatic-pre-CSS#2]
«Миксование — наличие класса БЕМ-блока и класса БЭМ-элемента у одного тега»

**Comment by nicothin** [comment]
Угу, спасибо/
Там что-то дофига этих опечаток было )))
https://github.com/nicothin/idiomatic-pre-CSS/commit/b4fe63c69fa6c53bd18af91194f1f2c55175973b
