### ISSUE TITLE
Элемент может быть физически за пределами блока

### ISSUE THREAD

**Issue by ihorzenich** [nicothin/idiomatic-pre-CSS#4]
В случае острой необходимости элемент может находится физически за пределами блока в DOM.
Пруф: https://en.bem.info/forum/43/

**Comment by nicothin** [comment]
В обоих случаях по ссылке элемент находится внутри своего блока, а не вне.
Табуляция показывает вложенность.

**Comment by ihorzenich** [comment]
@nicothin примеры - для второго вопроса - могут ли блоки и элементы быть произвольно вложены друг в друга. Для первого вопроса - может ли блок находится за пределами элемента примера нет. Добавляю кстати, спасибо.

Этот вопрос специально создавали именно чтоб было куда ссылаться что так можно.

**Comment by nicothin** [comment]
странно там получается, адепт уже ответил, а потом вы поменяли вопрос )

сейчас там 2 пример кода, 1 — ошибка, не БЭМ, 2 — корректный БЭМ.

**Comment by ihorzenich** [comment]
Это не ошибка, это правильный код.
Вот тут в Slack Веб-стандартов мы с @vithar это обсуждаем и решаем что нужно сделать постановочный вопрос и ответить на него на форуме, чтоб был пруф что так можно.
<img width="1218" alt="screen shot 2016-11-24 at 5 06 30 pm" src="https://cloud.githubusercontent.com/assets/1684521/20603057/6aea440e-b268-11e6-8ea4-3c675b70d31a.png">
<img width="1212" alt="screen shot 2016-11-24 at 4 59 09 pm" src="https://cloud.githubusercontent.com/assets/1684521/20602780/6d97e66c-b267-11e6-9850-cb49cc96075f.png">

Я не менял вопрос, я просто добавил пример кода для первого вопроса, чтоб было наглядней. Вопрос там четко поставлен: "могут ли элементы в DOM располагаться за пределами блока" и ответ - "да".

**Comment by nicothin** [comment]
кажется, пришло время создавать свой БЭМ с блекджеком и смыслом :D:D:D

**Comment by nicothin** [comment]
http://nicothin.github.io/idiomatic-pre-CSS/#bem-elem-in — добавил данные об использовании элемента вне блока.
Что ж поделать, раз Харисов сказал... )))
