### ISSUE TITLE
Блок «Всегда являются БЭМ-блоками» дублируется

### ISSUE THREAD

**Issue by ihorzenich** [nicothin/idiomatic-pre-CSS#8]
Блок «Всегда являются БЭМ-блоками» дублируется на странице 2 раза:

1. Напротив «Как отличить БЭМ-блок и БЭМ-элемент»
2. Напротив «Некоторые фрагменты дизайна — всегда БЭМ-блоки»

Стоит объединить эти блоки.

**Comment by nicothin** [comment]
Пожалуй.
Объединил.
